namespace: ha-test

homeAssistant:
  pvc:
    size: 9Gi
  hostNetwork: false
  privileged: false
  bluez:
    enabled: false
  matter:
    enabled: false
  devices:
    zigbee:
      enabled: false
    dbus:
      enabled: false
  plugins: []
  config:
    defaultConfig: true
    http:
      useXForwardedFor: true
      trustedProxies:
        - 10.0.0.0/16
        - 127.0.0.1

zwavejs:
  enabled: true
  devices:
    zwave:
      path: ""

mosquitto:
  enabled: true

gateway:
  enabled: false
